module.exports = {
  title: 'Plant Theatres & More',
  name: 'Plant Theatres & More',
  description: 'We manufacture a range of quality wooden and steel garden related products including plant theatres, bee houses, insect houses and bird boxes.',
  url: 'https://planttheatresandmore.co.uk',
  localUrl: 'http://localhost:8080',
  language: "English",
  lang: "en",
  dir: "ltr",
  locale: "en_GB",
  email: 'info@planttheatresandmore.co.uk',
  authorName: 'Will Moody',
  slogan: 'Hand-crafted in Norfolk',
  mobile: '07847300332',
  mobileDisplay: '07847 300332',
  telephone: '01603717057',
  telephoneDisplay: '01603 717057',
  intPhone: '+447847300332',
  address: '11 Blofield Corner Road',
  village: 'Blofield',
  city: 'Norwich',
  county: 'Norfolk',
  postcode: 'NR13 4SA',
  whatThreewords: 'contact.messed.clattered',
  latitude: '52.64869',
  longitude: '1.4332',
  instaSite: 'https://instagram.com/Planttheatres',
  facebookSite: 'https://instagram.com/Planttheatres',
  opens: '09:00',
  closes: '17:00',
  priceRange: '£15 - £200',
  generator: 'Eleventy 2.0.0',
  themeColor: '#ffffff',
  feedDescription: 'Our feed from the great articles we produce about garden and nature related stuff'
}
