const htmlmin = require('html-minifier-terser');
const buildDir = '_site';

const shouldTransformHTML = outputPath =>
  outputPath && outputPath.endsWith('.html') && process.env.ELEVENTY_ENV === 'production';

const isHomePage = outputPath => outputPath === `${buildDir}/index.html`;

process.setMaxListeners(Infinity);
module.exports = {
  htmlmin: function (content, outputPath) {
    if (shouldTransformHTML(outputPath)) {
      return htmlmin.minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        minifyJS: {
          compress: {
            arrows: false
          }
        },
        processScripts: 'application/ld+json',
        removeComments: true,
        useShortDoctype: true
      });
    }
    return content;
  }
};
